fix prices
2omb/3omb-frontend pull request #4
Opened 2022-02-09 23:38 UTC by chinochao

- added 2omb abi to the abi deployment
- created 2 new functions that use abi to pull the price and disabled coingecko.

2022-02-10 04:45 UTC, zander2omb commented on src/tomb-finance/TombFinance.ts
> +  const price = await fetch("https://api.coingecko.com/api/v3/simple/price?ids=2omb-finance&vs_currencies=usd").then(res => res.json())
let's remove or comment this out, since we don't use the coingecko result

2022-02-10 04:49 UTC, chinochao commented on src/tomb-finance/TombFinance.ts
> +  const price = await fetch("https://api.coingecko.com/api/v3/simple/price?ids=2omb-finance&vs_currencies=usd").then(res => res.json())
I forgot to comment those out. I was using to troubleshoot. I will send a new commit

2022-02-10 04:51 UTC, zander2omb requested changes
Looks mostly good - just needs some cleanup

2022-02-10 04:51 UTC, zander2omb commented on src/tomb-finance/TombFinance.ts
> +  console.log('COINGECKO PRICE',{ priceInDollars: price["2share"].usd })
same here - can remove

2022-02-10 04:51 UTC, zander2omb commented on src/tomb-finance/deployments/deployments.mainnet_old.json
> +{
this is handled best by git - let's remove .old

2022-02-10 04:59 UTC, chinochao commented
@zander2omb cleaned up the the coingecko, I forgot to do that before the push, and remove the _old.json

2022-02-10 05:35 UTC, zander2omb approved these changes
Verified new ABI addresses correspond to 2omb contracts. LGTM

2022-02-12 12:01 UTC, merged

2022-02-12 12:01 UTC, 2omb commented
commite